### ISSUE TITLE
'update FAILED' even though it does not

### ISSUE THREAD

**Issue by ChaosBlades** [truecharts/truetool#102]
### App Name

TrueTool

### SCALE Version

22.02.3

### App Version

v4.0.0

### Application Events

```Shell
bash truetool.sh -vsUp
  _______               _____ _                _       
 |__   __|             / ____| |              | |      
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___ 
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |                
    | |_ __ _   _  ___| | ___   ___ | |                
    | | '__| | | |/ _ \ |/ _ \ / _ \| |                
    | | |  | |_| |  __/ | (_) | (_) | |                
    |_|_|   \__,_|\___|_|\___/ \___/|_|                
                                                       
                                                       
Checking for updates...
TrueTool requires update
script updated
restarting script after update...
Checking for updates...
script up-to-date

Starting Catalog Sync...
Catalog sync complete
App Updater
Default Timeout: 500

Creating list of Apps to update...
No apps added to ignore list, continuing...


29 update(s) available:
drawio
flaresolverr
fluidd
freshrss
gaps
handbrake
home-assistant
jdownloader2
kavita
lidarr
mosquitto
node-red
openspeedtest
overseerr
plex
protonmail-bridge
prowlarr
qbittorrent
radarr
radarr-uhd
readarr
scrutiny
sonarr
sonarr-uhd
tautulli
tinymediamanager
trilium-notes
unifi
zigbee2mqtt

Updating Apps...

Waiting for update results...
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
Updating..
trilium-notes: update FAILED
flaresolverr: update FAILED
jdownloader2: update FAILED
freshrss: update FAILED
Updated fluidd
1.20.0_2.0.31
1.20.0_2.0.32
Updated mosquitto
2.0.15_6.0.32
2.0.15_6.0.34
Updated drawio
20.2.6_2.0.39
20.2.6_2.0.40
Updated sonarr
3.0.9.1549_11.0.30
3.0.9.1549_11.0.31
Verifying Active..
Verifying Active..
Updated plex
1.28.1.610_10.2.2
1.28.2.610_10.2.4
Updated openspeedtest
latest_1.0.28
latest_1.0.29
Updated zigbee2mqtt
1.27.0_4.0.29
1.27.0_4.0.31
Updated unifi
7.2.92_11.0.29
7.2.92_11.0.30
Updated qbittorrent
4.4.3.1_11.0.30
4.4.3.1_11.0.31
Updated overseerr
1.29.1_6.0.28
1.29.1_6.0.29
Updated prowlarr
0.4.4.1947_6.0.32
0.4.4.1947_6.0.33
Updated scrutiny
0.5.0_3.0.27
0.5.0_3.0.28
Updated node-red
3.0.2_11.0.31
3.0.2_11.0.32
Updated tautulli
2.10.3_11.0.30
2.10.3_11.0.31
Updated gaps
0.10.4_11.0.29
0.10.4_11.0.30
Updated readarr
0.1.1.1352_11.0.26
0.1.1.1352_11.0.27
Updated tinymediamanager
4.3.3_2.0.30
4.3.3_2.0.31
Updated home-assistant
2022.8.7_15.0.46
2022.8.7_15.0.47
Updated lidarr
1.1.0.2600_11.0.26
1.1.0.2600_11.0.27
Updated protonmail-bridge
1.8.10_6.0.27
1.8.10_6.0.28
Updated sonarr-uhd
3.0.9.1549_11.0.30
3.0.9.1549_11.0.31
Updated kavita
0.5.5_2.0.30
0.5.5_2.0.31
Updated radarr-uhd
4.1.0.6175_11.0.29
4.1.0.6175_11.0.30
Updated radarr
4.1.0.6175_11.0.29
4.1.0.6175_11.0.30
Updated handbrake
1.25.1_13.0.29
1.25.1_13.0.30
Verifying Active..
Verifying Active..
Active
Active
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Verifying Active..
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Active
Docker Prune
Pruning Docker Images...
Total reclaimed space: 2.054GB
Docker Prune Successfull
```

### Application Logs

```Shell
I see multiple listings of the following types of errors in the Task Manager

Error: [ENOENT] None: ChartRelease freshrss does not exist

catalog.items
Error: Failed connection handshake

chart.release.pull_container_images
Error: [EFAULT] Unable to connect to kubernetes cluster
```

### Application Configuration

bash truetool.sh -vsUp

### Describe the bug

When updating a large number of containers (29 in this example) some containers 'FAILED' to update but once checking in TrueNAS the containers are up to date.

### To Reproduce

1. Run the script and have a lot of updates available.
2. Receive errors that some updates 'FAILED' even though they do not.

### Expected Behavior

Not receive erroneous error messages.

### Screenshots

![Screenshot from 2022-08-30 15-46-43](https://user-images.githubusercontent.com/7530545/187529486-28a1b947-f61e-40a9-91f1-52434fb3c8ae.png)

### Additional Context

I think this is due to it trying to update too many containers at one time overloading either the local server or the remote update server. If TrueTool does not find too many updates I have never gotten these errors, only after the weekly TrueCharts update when almost every container gets an update.

I don't believe this is due to an under powered server. I have dual Intel Xeon E5-2680 v3 (12c24t) and 128GB of RAM. Containers are hosted on M.2 NVMe. Network connection is 10GbE to a pfSense router with 1GbE internet.

Edit: Also, just adding that the containers that report failing to update are seemingly random every time. The number that fail also seems to be random. I believe I have seen as many as 8 and as few as 3. But like I said they actually do end up updating in the end.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by ChaosBlades** [comment]
Due to a scheduling issue it looks like the Major and Minor update commands were trying to run at the same time. This very well may have been my issue. Leaving this open for now until the next major update merge.

**Comment by Ornias1993** [comment]
as you can see a big PR/update is already being worked on.

**Comment by ChaosBlades** [comment]
Finally a big update has been pushed and I can confirm this is not my own stupidity. Something is going on here.
The error has changed slightly. Looks like 8 of the 11 containers that 'failed' are reporting updates are still available so I ran the script again. After that all were updated successfully despite it reporting `overseerr: update FAILED'

I did get these errors in Task History
`Error: [ENOENT] None: ChartRelease photoprism does not exist` (Each failed update got this)
`chart.release.upgrade | Error: Failed connection handshake`
`chart.release.pull_container_images | Error:` (error is blank)
Seem like the update server is just overloading and connections are timing out trying to simultaneously update multiple containers. I do have wired gigabit LAN and 1000/50 internet with a beefy pfSense router so I don't believe the issue is on my end of the connection.

I am also now getting an Alert email around the same time the script is running over the last 2 days.
`Failed to sync TRUECHARTS catalog: [EFAULT] Unexpected keyword arguments: 'additional_attrs'`

Created gist for both update logs as scrolling was getting a little extreme.
https://gist.github.com/ChaosBlades/0b9bc67ccf55800e965386526598b95a

**Comment by stavros-k** [comment]
> I am also now getting an Alert email around the same time the script is running over the last 2 days. Does not happen every sync as it didn't happen when I manually ran the script or during the general syncs it does in the background.
> `Failed to sync TRUECHARTS catalog: [EFAULT] Unexpected keyword arguments: 'additional_attrs'`

Not related with the truetool at all. (This was fixed within 24h)

**Comment by Ornias1993** [comment]
Solved in todays truetool update :)
