### ISSUE TITLE
Add Argument to update containers Sequentially instead of in Parallel

### ISSUE THREAD

**Issue by ChaosBlades** [truecharts/truetool#135]
### Is your feature request related to a problem?

I think this feature will resolve https://github.com/truecharts/truetool/issues/102. If I get ~5 or less updates I don't get any errors but any more than that and I get the errors mentioned in that issue. I think the remote update server or the route my internet is taking gets overloaded when TrueNAS SCALE tried to pull upwards of 35 container images at the same time.

### Describe the solution you'd like

Add a new Argument such as `--seq-updates` to update each container one at a time.
1. Check for updates
2. Downloads Container 1
3. Waits for Container 1 to Deploy
4. Downloads Container 2
5. Waits for Container 2 to Deploy
6. etc.

### Describe alternatives you've considered

Could also add a number after `--seq-updates #` to indicate how many containers to update at one time.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
The issue isnt parallel, its the amount of parallel tasks.

at the moment, due to a rework, we’re not accepting guthub issues for TrueTool
