### ISSUE TITLE
Backups: delete the most recent backups instead of the older ones

### ISSUE THREAD

**Issue by Simoneu01** [truecharts/truetool#2]
If I run the tool to backup it delete newest backups instead of older one.

**step to reproduce:**

1. truetool -b
2. truetool -l 
3. truetool -b 1
4. truetool -l

**Comment by Ornias1993** [comment]
-b 1 means "keep only one"

**Comment by Ornias1993** [comment]
Checked it, I really only see my last few backups.

**Comment by Simoneu01** [comment]
![E73F4D57-6545-4C9F-9CE0-36ABD8F55C58](https://user-images.githubusercontent.com/43807696/152322267-54cc5355-7ec8-46a4-98fb-ceecf188b752.png)

![018A1DCB-33E0-4958-A7E5-17936417CFF2](https://user-images.githubusercontent.com/43807696/152322317-82eaa1c2-ce46-4afc-a10d-54d72781f5ec.png)
![6E0581AB-2525-4378-8F8E-0BFD94B8759A](https://user-images.githubusercontent.com/43807696/152322329-2560870e-7a21-463d-9049-278be99e140b.png)
![49E3BAE5-BFFE-4FBF-B3C9-70F7C8ABB93B](https://user-images.githubusercontent.com/43807696/152322334-f1e7c009-a1fe-470d-b1a4-e128e3083c42.png)

**Comment by Ornias1993** [comment]
Ahh SHOOT i see the issue.
Months and days should be reversed.

**Comment by Ornias1993** [comment]
releasing fix as we speak! :)
Thanks for the headsup!

**Comment by Ornias1993** [comment]
Fix is up!
