### ISSUE TITLE
Garbled output when not running from shell

### ISSUE THREAD

**Issue by hugalafutro** [truecharts/truetool#201]
### App Name

truetool.sh

### SCALE Version

22.02.4

### App Version

latest (it autoupdates)

### Application Events

```Shell
n/a - truetool.sh issue
```

### Application Logs

```Shell
n/a - truetool.sh issue
```

### Application Configuration

n/a - truetool.sh issue

### Describe the bug

when running `bash truetool.sh --no-color -b 7 -sup` from cron, the email it sends contains some characters that are not present there when running the tool manually from shell.

### To Reproduce

add the cron task as desribed in the manual and observe the resulting email

### Expected Behavior

the weird characters should not be added

### Screenshots

![image](https://user-images.githubusercontent.com/30209689/200612054-3b9138b0-a21f-4f5f-82e6-8d404a7c8b3f.png)

I have tried sending the output to healtchecks instance with curl instead, but results are the same, when it runs from cron it loks like this:
![image](https://user-images.githubusercontent.com/30209689/200612203-71331614-1972-4240-a786-c49bd1768947.png)

In both instances if I run the same command from shell I receive the same output without the added characters.

### Additional Context

I got nothing.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Solved in todays truetool update :)
