### ISSUE TITLE
Automated fix to breaking changes in helm charts

### ISSUE THREAD

**Issue by Lockszmith-GH** [truecharts/truetool#216]
### Is your feature request related to a problem?

Recently [[1](https://discord.com/channels/830763548678291466/830763549156573216/1040610406357532772)][[2](https://www.reddit.com/r/truenas/comments/ysf8l3/comment/ivzw1p1)], old helm charts fail to upgrade when they have 'simplePVC' and 'SimpleHP' Persistence and PersistentList entries.

I was hoping for an automated fix here, but since none existed with some trial and error, I ended up making one.

### Describe the solution you'd like

Have truetool be able to fix all 'old-style' charts automatically.

### Describe alternatives you've considered

Performing the task manually, one by one, is not only slow, but prone to human errors.

### Additional context

Full code of my solution will be posted in the first comment.

The reason I'm not posting a PR, is because I'm unsure the maintainers of this tool are interested in this, but this seems like a good 'central' place to put this for those who are interested.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Lockszmith-GH** [comment]
# The code below does the following:
1. Collects the list of apps with updates (uses `cli`), can be filtered via command-line parameter
2. For each app in the list:
   1. Grabs the helm values
   2. Check if there is any `simplePVC` or `simpleHP` entries, if not, skips
   3. Preps the `helm upgrade` command line parameters. For `simpleHP` a temp file is needed, as it is an array (see [helm issue](https://github.com/helm/helm/issues/8320#issuecomment-644875049) for more info)
   4. call `helm upgrade`

After this runs, `turetool -u/-U` should work once again

# The code
```
#! /usr/bin/env bash
set -e

function callhelm() {
    env sudo KUBECONFIG=/etc/rancher/k3s/k3s.yaml env helm "${@}"
}

APP_LIST="$( \
    sudo cli \
        -m csv \
        -c 'app chart_release query name,update_available,human_version,human_latest_version,container_images_update_available,status' \
    | tail +2 \
    | grep -E ",true(,|$)" \
    | grep -E "${1}" \
    | sort \
    | sed 's/_/,/g' \
    | cut -d',' -f 1,5 \
    | tr ',' ' ' \
)"

[[ -z "$APP_LIST" ]] && printf "No apps found, exiting." && exit || true

TMP_VAL_FILE=$(mktemp ${TMPDIR:-/tmp}/tmp-helm-values.XXXXX)
READY_APPS=()
while read app_info; do
    APP_INFO=($app_info)
    APP=${APP_INFO[0]}
    VER=${APP_INFO[1]}
    printf '' > $TMP_VAL_FILE

    APP_CONFIG=$(callhelm get values --namespace=ix-${APP} ${APP} --output json)

    SIMPLE_PVC=$( echo "$APP_CONFIG" | jq -r ' .persistence | to_entries[] | select( .value.type == "simplePVC" ) | .key ' 2>/dev/null ) || true
    NEW_VALS=''
    [[ -n "$SIMPLE_PVC" ]] && while read entry; do
        NEW_VALS="$NEW_VALS --set 'persistence.${entry}.type=pvc' --set 'persistence.${entry}.size=999Gi'"
    done < <( echo "$SIMPLE_PVC" )
    SIMPLE_HOST=$( \
        echo "$APP_CONFIG" \
        | jq -r ' .persistenceList[] | select( .type == "simpleHP" ) | .hostPathSimple ' 2>/dev/null \
    ) || true # don't stop if failed
    if [[ -n "$SIMPLE_HOST" ]]; then
        echo "$APP_CONFIG" \
            | jq ' { "persistenceList": .persistenceList }' \
            | sed 's/"simpleHP"/"hostPath"/g; s/Simple"/"/g' \
            > $TMP_VAL_FILE
        NEW_VALS="$NEW_VALS --values '$TMP_VAL_FILE'"
    fi

    [[ -z "$NEW_VALS" ]] && continue || true

    1>&2 printf "App: %s | Pvc: %s | Host: %s\n" \
        "$APP" \
        "$( echo "$SIMPLE_PVC" | paste -sd',' )" \
        "$( echo $SIMPLE_HOST | paste -sd';' )"
    CMD=$( printf "%s" \
        "helm upgrade '--namespace=ix-${APP}' '${APP}' 'TrueCharts/${APP}' '--version=${VER}' --reuse-values ${NEW_VALS}" \
    )
    printf "%s\n" "$CMD"
    eval "call$CMD" || continue

    READY_APPS+=($APP)
done < <( echo "$APP_LIST" )

rm "$TMP_VAL_FILE" || true # don't fail on this.
```

**Comment by Ornias1993** [comment]
This can already be done using the migration toolkit for TrueNAS SCALE Apps. We’ve chosen not to put said time into it.

SCALE apps should also NEVER EVER be eddited using helm or kubectl tools.

Your free to PR bative SCALE python migration scripts, but thats not a truecharts related project.


Also: users should not use TrueTool for breaking changes

**Comment by Lockszmith-GH** [comment]
I had a feeling "I'm doing it wrong" - at least I learned a bit about helm through it.
I'll check the migration toolkit, as I was not aware of that.
I'll also add a disclaimer above the code, so that whoever tries venturing there, have the proper cautions.
