### ISSUE TITLE
Truetool keeps trying to apply a hotpatch. Unknown if patch suceeds or fails - no version number that I can find

### ISSUE THREAD

**Issue by aardvarkl** [truecharts/truetool#256]
### App Name

truetool

### SCALE Version

22.12.0

### App Version

Unknown - whatever I just downloaded from git. Can't find a version number

### Application Events

```Shell
Truetool whenever it runs does the following:

Starting hotpatcher...
Applying 22.12 HotPatch 1
download completed
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file plugins/chart_releases_linux/chart_release.py.rej
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file plugins/chart_releases_linux/resources.py.rej
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file plugins/chart_releases_linux/scale_workload.py.rej
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file plugins/kubernetes_linux/restore.py.rej
patch failed or skipped, not critical
```

### Application Logs

```Shell
Unaware of any logs
```

### Application Configuration

No changes
I deleted the previous version to see if this would fix things. Re-ran the git clone and ran the script. Not much else I can do

### Describe the bug

Running ./truetool.sh -p (for example) ghenerates each time patch errors
``Starting hotpatcher...
Applying 22.12 HotPatch 1
download completed
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file plugins/chart_releases_linux/chart_release.py.rej
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file plugins/chart_releases_linux/resources.py.rej
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file plugins/chart_releases_linux/scale_workload.py.rej
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file plugins/kubernetes_linux/restore.py.rej
patch failed or skipped, not critical
``

### To Reproduce

Just run the script and do something that involves the patched. Prune is a good option

### Expected Behavior

After doing the patch once I would expect it not to happen again

I don't know if the patch worked or failed as there appears to be no version number

### Screenshots

n/a

### Additional Context

n/a

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
As clearly stated:
`patch failed or skipped, not critical`

The error is NOT critical.
