### ISSUE TITLE
Wrong backup name displayed

### ISSUE THREAD

**Issue by fmunteanu** [truecharts/truetool#28]
### App Name

truetool

### SCALE Version

22.02.1

### App Version

1.0

### Application Events

```Shell
n/a
```

### Application Logs

```Shell
n/a
```

### Application Configuration

n/a

### Describe the bug

Backup does not takes the given name.

### To Reproduce

```
root@uranus[/mnt/software/truetool]# bash truetool.sh -b 1
  _______               _____ _                _
 |__   __|             / ____| |              | |
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |
    | |_ __ _   _  ___| | ___   ___ | |
    | | '__| | | |/ _ \ |/ _ \ / _ \| |
    | | |  | |_| |  __/ | (_) | (_) | |
    |_|_|   \__,_|\___|_|\___/ \___/|_|


Checking for updates...
script up-to-date

Backup Tool

Number of backups was set to 1

New Backup Name:
test
TrueTool_2022_06_26_15_53_20
root@uranus[/mnt/software/truetool]# test
root@uranus[/mnt/software/truetool]# bash truetool.sh --list-backups
  _______               _____ _                _
 |__   __|             / ____| |              | |
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |
    | |_ __ _   _  ___| | ___   ___ | |
    | | '__| | | |/ _ \ |/ _ \ / _ \| |
    | | |  | |_| |  __/ | (_) | (_) | |
    |_|_|   \__,_|\___|_|\___/ \___/|_|


Checking for updates...
script up-to-date

Backup Listing Tool
pulling all restore points..
Detected Backups:
1  TrueTool_2022_06_26_15_53_20
```

### Expected Behavior

I expect to see the backup named `test`.

### Screenshots

n/a

### Additional Context

n/a

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
The new backup is not named "test", most likely the `test` reference is shown due to a parser error and possible related to a custom created backup named `test` or something similair.

Your actually backup seems to be called:
`TrueTool_2022_06_26_15_53_20`

**Comment by fmunteanu** [comment]
@Ornias1993 run the script, you will see it stops and "asks" you for a backup name:

```
New Backup Name:

```

I thought this is a prompt to enter a backup name, but in fact it waits to automatically generate a backup name. I'm going to create a feature request to input a backup name format.
