### ISSUE TITLE
--mount failed, show "mountPVC: command not found"

### ISSUE THREAD

**Issue by troyliu0105** [truecharts/truetool#286]
### App Name

truetool

### SCALE Version

22.12.0

### App Version

9a7a7841b7e333501fc70ce62948e555598ad5bd

### Application Events

```Shell
_______               _____ _                _
 |__   __|             / ____| |              | |
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |
    | |_ __ _   _  ___| | ___   ___ | |
    | | '__| | | |/ _ \ |/ _ \ / _ \| |
    | | |  | |_| |  __/ | (_) | (_) | |
    |_|_|   \__,_|\___|_|\___/ \___/|_|


Checking for updates...
script up-to-date

Starting hotpatcher...
Applying 22.12 HotPatch 1
download completed
Patch Already Applied
Applying 22.12 HotPatch 2
download completed
Patch Already Applied
/root/truetool/truetool.sh: line 182: mountPVC: command not found
```

### Application Logs

```Shell
above
```

### Application Configuration

just a fresh install via git clone. no additional config

### Describe the bug

can't use `--mount` command

### To Reproduce

run `bash /root/truetool/truetool.sh --mount`

### Expected Behavior

a list to use pvc to mount 

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Stupid Typo, thanks for noticing :)

**Comment by troyliu0105** [comment]
thanks, it works now.
