### ISSUE TITLE
Define backup name

### ISSUE THREAD

**Issue by fmunteanu** [truecharts/truetool#29]
### Is your feature request related to a problem?

I like the backup name to have a more programatic way of being identified, something like `servername-2022-02-15`.

### Describe the solution you'd like

Implement a switch called `--format`:

```
bash truetool.sh --no-color -b 1 --format uranus-$(date +%s)
```

### Describe alternatives you've considered

n/a

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Not going to implement this.
If you want something like this, use the SCALE API directly.

We just offer this as an easy entrypoint to triggering the scale API calls and are not going to offer this amount of customisation.
Making changes in those portions of the code, might lead to people's backups being wiped, which is also not something i'm keen to do.
