### ISSUE TITLE
Addressing Helm Upgrade Issues

### ISSUE THREAD

**Issue by Emalton** [truecharts/truetool#294]
### Is your feature request related to a problem?

Yes, sometimes there can be a problem updating helm apps, it would be great if there was a TrueTool option to automatically fix these issues, as explained by Stavros in the [Discord server](https://discord.com/channels/830763548678291466/1051965552458993787/1052261256033226762). 

Here's the steps that are mentioned there, for those of you who aren't in the Discord. Credit to Stavros for this.
(Information below is in refence to Authelia, but this can be adapted to any application it seems.)

----------------------

**Description of Error:**
`Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress`

**Steps:**
Helm crapped and has a release stuck
`k3s kubectl get secrets -n ix-authelia`
It will probably show something like `sh.helm.release.v1.authelia.v##`

Do `k3s kubectl get secrets -n ix-authelia sh.helm.release.v1.authelia.vNUMBERHERE -o yaml |  grep "status:"`

**NOTE. THIS MIGHT BREAK THE APP COMPLETELY**
It's just some things to "try". Cannot guarantee anything. And it's Outside of support.

`k3s kubectl describe deploy -n ix-authelia | grep helm-revision`

Check the output of this. This you want to keep

For any revision higher than this you want to do:
`k3s kubectl delete secret -n ix-authelia sh.helm.release.v1.authelia.vNUMBER`

Then Stop the app.
Then Start the app.
Then Edit the app and save without changes.

If all works, try to upgrade.
If it works cool. If not. reinstall

### Describe the solution you'd like

Automated fashion of the above commands.

### Describe alternatives you've considered

Manually

### Additional context

Feel free to change the issue name/description to something more suitable if needed.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Nothing to do with TrueTool.
Also not even a frequent issue either.

please dont request fixes for iX-Systems issues from TrueTool.
