### ISSUE TITLE
TrueTool returns exit code 1 after successful backup

### ISSUE THREAD

**Issue by kiler129** [truecharts/truetool#328]
### App Name

Truetool

### SCALE Version

22.12.0

### App Version

N/A (autoupdated)

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
# /mnt/admin/truetool/truetool.sh -b 7 ; echo $?
  _______               _____ _                _
 |__   __|             / ____| |              | |
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |
    | |_ __ _   _  ___| | ___   ___ | |
    | | '__| | | |/ _ \ |/ _ \ / _ \| |
    | | |  | |_| |  __/ | (_) | (_) | |
    |_|_|   \__,_|\___|_|\___/ \___/|_|


Checking for updates...
script up-to-date

Starting hotpatcher...
Applying 22.12 HotPatch 1
download completed
Patch Already Applied
Applying 22.12 HotPatch 2
download completed
Patch Already Applied
Running Apps Backup
🄱 🄰 🄲 🄺 🅄 🄿 🅂
Number of backups was set to 7

New Backup Name:
TrueTool_2023_02_01_03_58_42

Deleted the oldest backup(s) for exceeding limit:
TrueTool_2023_02_01_03_36_57


1
```

### Application Configuration

N/A

### Describe the bug

When running TrueTool backup utility, the final exit code denotes error condition (`1`) despite the backup succeeding. This causes monitoring tools to be unable to distinguish real backup failure from success.

### To Reproduce

1. Run `/mnt/admin/truetool/truetool.sh -b 7`
2. Run `echo $?`

### Expected Behavior

Exit code should be 0 after successful backup.

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by ekrunch** [comment]
Same issue for me. TNS 22.12, same problem. Always shows an error in my TNS console b/c of the exit code of 1, despite it being successful. The command I use is this...

`/<path>/truetool.sh --no-color -b 31`

**Comment by Ornias1993** [comment]
No color is deprecated though…

**Comment by kiler129** [comment]
> No color is deprecated though…

I'm running without `--no-color` and it still returns `1`.

**Comment by ekrunch** [comment]
Might want to update the README under "Creating a Cron Job" too. 

But to the point that @kiler129 made, it still reports error level 1. Output below

`*[main][/mnt/zpool-spinning1/scripts/truetool]$ /mnt/zpool-spinning1/scripts/truetool/truetool.sh -b 31
  _______               _____ _                _
 |__   __|             / ____| |              | |
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |
    | |_ __ _   _  ___| | ___   ___ | |
    | | '__| | | |/ _ \ |/ _ \ / _ \| |
    | | |  | |_| |  __/ | (_) | (_) | |
    |_|_|   \__,_|\___|_|\___/ \___/|_|


Checking for updates...
script up-to-date

Starting hotpatcher...
No hotpatch available for your version, congratulations!
Running Apps Backup
🄱 🄰 🄲 🄺 🅄 🄿 🅂
Number of backups was set to 31

New Backup Name:
TrueTool_2023_02_26_14_40_33

Deleted the oldest backup(s) for exceeding limit:
TrueTool_2023_01_27_00_00_05


*[main][/mnt/zpool-spinning1/scripts/truetool]$ echo $?
1`

**Comment by Ornias1993** [comment]
> Might want to update the README under "Creating a Cron Job" too.
> 
> But to the point that @kiler129 made, it still reports error level 1. Output below
> 
> `*[main][/mnt/zpool-spinning1/scripts/truetool]$ /mnt/zpool-spinning1/scripts/truetool/truetool.sh -b 31
> 
> |__ **| / ____| | | | | |_ __ _ _ _**| | | |** __ _ _ __| |_ ___ | | '__| | | |/ _ \ | | '_ \ / _` | '**| __/ **| | | | | |_| | __/ |____| | | | (_| | | | |___ **|_|_| __,_|_**|_____|_| |_|__,_|_| __|**_/ |__ **| |** __| | | | |_ __ _ _ _**| | ___ ___ | | | | '**| | | |/ _ \ |/ _ \ / _ | | | | | | |_| | **/ | (_) | (_) | | |_|_| __,_|_**|_|___/ ___/|_|
> 
> Checking for updates... script up-to-date
> 
> Starting hotpatcher... No hotpatch available for your version, congratulations! Running Apps Backup 🄱 🄰 🄲 🄺 🅄 🄿 🅂 Number of backups was set to 31
> 
> New Backup Name: TrueTool_2023_02_26_14_40_33
> 
> Deleted the oldest backup(s) for exceeding limit: TrueTool_2023_01_27_00_00_05
> 
> *[main][/mnt/zpool-spinning1/scripts/truetool]$ echo $? 1`

We don't really need +1 comments, I think the issue is quite clear already...

**Comment by Ornias1993** [comment]
Closed, see: https://truecharts.org/news/the-future
