### ISSUE TITLE
Containers not being mounted in Truetool

### ISSUE THREAD

**Issue by StevenMcElligott** [truecharts/truetool#33]
### App Name

Truetool

### SCALE Version

22.02.1

### App Version

Latest

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

bash /mnt/Storage/Apps/Scripts/truetool/truetool.sh

### Describe the bug

Can't mount containers using the menu, gives you above error

### To Reproduce

Run bash /mnt/Storage/Apps/Scripts/truetool/truetool.sh
Select 2.
Pick App
Get error

### Expected Behavior

Container is mounted to /temporary

### Screenshots

![image](https://user-images.githubusercontent.com/89483932/176786072-94a78eb8-69b7-468a-867c-1a0676873980.png)

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by luqasn** [comment]
I have the same issue (because of the replication I have configured), it could make sense to do `dataset=$(cli -c 'app kubernetes config' | grep dataset | awk -F '|' '{print $3}' | xargs)` first and then make sure to `zfs list | grep ^$dataset`.

**Comment by Ornias1993** [comment]
Please no +1 comments or attempts to “help”.
Its not lack if skill, its time.

**Comment by Ornias1993** [comment]
Solved in todays truetool update :)
