### ISSUE TITLE
default option for additional mounting not handled correctly

### ISSUE THREAD

**Issue by hros** [truecharts/truetool#353]
### App Name

truetool

### SCALE Version

22.02.3

### App Version

22.12.2

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

N/A

### Describe the bug

After mounting a PVC the following message is displayed:

> Would you like to mount anything else? (y/N):

It seems that pressing `Enter` would select the default (uppercase 'N') , however pressing `Enter` returns

> Invalid selection "" was not an option

### To Reproduce

1. start TrueTool
2. mount a PVC
3. press enter at the prompt

### Expected Behavior

script should accept the default (pressing Enter) or print the message with a lower case 'n'

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Closed, see:
https://truecharts.org/news/the-future
