### ISSUE TITLE
Update command returns exit code 1 when no updates are available

### ISSUE THREAD

**Issue by matiasba** [truecharts/truetool#61]
### App Name

truetool

### SCALE Version

22.02.1

### App Version

main

### Application Events

```Shell
#Have all apps up to date and run update command
bash /root/truetool/truetool.sh -u
#Check response code
echo $?
```

### Application Logs

```Shell
root@freenas[~]# bash /root/truetool/truetool.sh --no-color -u
  _______               _____ _                _
 |__   __|             / ____| |              | |
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |
    | |_ __ _   _  ___| | ___   ___ | |
    | | '__| | | |/ _ \ |/ _ \ / _ \| |
    | | |  | |_| |  __/ | (_) | (_) | |
    |_|_|   \__,_|\___|_|\___/ \___/|_|


Checking for updates...
script up-to-date

App Updater
Default Timeout: 500

Creating list of Apps to update...
No apps added to ignore list, continuing...


There are no updates available or middleware timed out
root@freenas[~]# echo $?
1
```

### Application Configuration

jellyfin, sonnar and jacket apps installed plus a pihole docker image

### Describe the bug

Update command returns exit code 1 when no updates are available

### To Reproduce

.

### Expected Behavior

The return code should be 0

### Screenshots

.

### Additional Context

.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Fixed a long time ago afaik

**Comment by matiasba** [comment]
I just checked and it is not fixed in the latest version. @Ornias1993 please reopen :)

![image](https://user-images.githubusercontent.com/15465574/211207537-f6234f21-8a66-4f8f-90c4-f7202c1ae8a5.png)

**Comment by matiasba** [comment]
I'm not very familiar with this code but changing the "return 0" to "exit 0" in this line seems to fix it.
https://github.com/truecharts/truetool/blob/edad9f9a1b770a8cb225b15d25d8ed732844ff28/functions/update_apps.sh#L7
